### ISSUE TITLE
Pass promise resolutions through series

### ISSUE THREAD

**Issue by boo1ean** [dbrockman/promise-flow#10]
What do you think about passing promise resolution in series method?
Will be very useful, since it allows to make proper functions composition.

replace this https://github.com/dbrockman/promise-flow/blob/master/src/index.js#L16
with this `promise = promise.then((res) => f(res))`;

**Comment by boo1ean** [comment]
I've came to the following implementation, if you interested https://github.com/boo1ean/pflow/blob/master/index.js

**Comment by dbrockman** [comment]
@boo1ean Yeah. I almost added a `compose` or `pipe` function but I wanted to limit the functions to what I actually used in real projects.
