### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by boo1ean** [dbrockman/promise-flow#11]
For node runtimes which don't have Promise yet: `ReferenceError: Promise is not defined`

**Comment by dbrockman** [comment]
@boo1ean I will make it more clear in the readme that this module does not include a shim for `Promise`. I think it's better to include a shim outside of the module if used in an older version of node (or browser).

[es6-promise](https://www.npmjs.com/package/es6-promise) is a good choice, I will link to that.
